name: dbt + SQLFluff CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-duckdb sqlfluff

      - name: Lint SQL with SQLFluff
        run: |
          sqlfluff lint models/ --config sqlfluff.toml

      - name: Run dbt deps
        run: dbt deps

      - name: Run dbt compile
        run: dbt compile

      - name: Run dbt run
        run: dbt run

      - name: Run dbt test
        run: dbt test 